### ISSUE TITLE
Support for validating test cards

### ISSUE THREAD

**Issue by theogravity** [continuationlabs/credit-card#21]
I had a PR a long time ago regarding support for test cards (https://github.com/continuationlabs/credit-card/pull/17) - the response was reasonable given that if you're using a test card number that's *valid* and it's not being considered as valid, it should be a bug, but what about scenarios where the card number is invalid?

For example:
http://developer.ean.com/docs/test-booking-procedures/

Uses 5401999999999999 which is an invalid number.

**Comment by cjihrig** [comment]
Can you try defining your own card type - https://github.com/continuationlabs/credit-card#defining-custom-card-types. Using that approach, you should be able to validate cards however you choose.
