### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by eloypnd** [continuationlabs/credit-card#23]
Hi guys!

We are having some issues with Internet Explorer. [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) is not supported in Explorer. And _"assigning"_ objects like [here](https://github.com/continuationlabs/credit-card/blob/master/lib/index.js#L90) and [here](https://github.com/continuationlabs/credit-card/blob/master/lib/index.js#L238) are causing _Syntax Error_ in all versions of Explorer.

Will you accept a PR to fix this issues?

**Comment by cjihrig** [comment]
Closing per #24
