### ISSUE TITLE
Uglify issue

### ISSUE THREAD

**Issue by lancecarlson** [continuationlabs/credit-card#28]
I'm still trying to track down the exact problem, but I'm running node 4.4.6 and I just tried to uglify your package and got an error. I think it was having issues parsing 'let', so I think I need to upgrade my node to 5 in order to actually uglify your code. Will it be a requirement to use node 5 in order to use your lib? if so, it should be indicated somewhere.

**Comment by cjihrig** [comment]
`let` is supported in Node v4. Also, we run v4 in our CI (see .travis.yml). Sounds like an uglify issue.

**Comment by lancecarlson** [comment]
FYI, you were right. Needed to use uglify on the harmony branch.
