### ISSUE TITLE
Error on Webpack -p [Build is breaking on using Credit-Card with UglifyJS]

### ISSUE THREAD

**Issue by raviroshan** [continuationlabs/credit-card#36]
When running Webpack to build the app in dev mode, it is generating the bundle.js successfully.

But running Webpack -p is kicking in UglifyJS and that is breaking because of credit-card module.
**SyntaxError: Unexpected token: name (_defaults) [./~/credit-card/lib/index.js:5,0]**

Attaching screenshot for your reference.
![uglify](https://cloud.githubusercontent.com/assets/5485092/23069316/f4786d00-f54c-11e6-9733-8e728f96eea4.png)

**Comment by cjihrig** [comment]
This is an issue with Uglify. The problem is that Uglify doesn't understand ES 6 (see https://github.com/mishoo/UglifyJS2/issues/448 and https://github.com/mishoo/UglifyJS2/issues/659). You'll have to transpile this module down to ES5 to make it work.
